name: TypeScript Linting, Build, and Tests

on:
  push:
    branches: [ 'ci' ]
  pull_request:
    branches: [ 'ci' ]

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch Artifactory secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          method: jwt
          path: jwt-github-actions
          role: github-${{ github.repository_owner }}-${{ github.event.repository.name }}
          url: https://vault.bendingspoons.com
          secrets: |
            static2/data/github/shared/ci/manual ARTIFACTORY_USERNAME ;
            static2/data/github/shared/ci/manual ARTIFACTORY_ACCESS_TOKEN

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install Dependencies
        run: |
          npm ci \
            --progress=plain \
            --secret id=ARTIFACTORY_ACCESS_TOKEN,env=ARTIFACTORY_ACCESS_TOKEN \
            --secret id=ARTIFACTORY_USERNAME,env=ARTIFACTORY_USERNAME

      - name: Run Linter
        run: npm run lint

      - name: Authenticate to GCP using Workload Identity
        uses: google-github-actions/auth@v2
        with:
          service_account: deploy@<handle>-training-42@.iam.gserviceaccount.com
          workload_identity_provider: projects/286246949275/locations/global/workloadIdentityPools/github-actions/providers/bendingspoons

      - name: Build Project
        run: |
          npm run build \
            --progress=plain \
            --secret id=ARTIFACTORY_ACCESS_TOKEN,env=ARTIFACTORY_ACCESS_TOKEN \
            --secret id=ARTIFACTORY_USERNAME,env=ARTIFACTORY_USERNAME

      - name: Run Tests
        run: npm test
