name: CI Pipeline

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master
      - ci

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (for linting and testing)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run lint checks
      - name: Run linter
        run: npm run lint

      # Step 5: Run unit tests
      - name: Run tests
        run: npm test
