name: TypeScript Linting and Tests

on:
  push:
    branches: [ 'ci' ]
  pull_request:
    branches: [ 'ci' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Project's .npmrc
        run: cp .npmrc ~/.npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test
