name: TypeScript Linting, Build, and Tests

on:
  push:
    branches: [ 'ci' ]
  pull_request:
    branches: [ 'ci' ]

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch Artifactory secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v3
        with:
          method: jwt
          path: jwt-github-actions
          role: github-${{ github.repository_owner }}-${{ github.event.repository.name }}
          url: https://vault.bendingspoons.com
          secrets: |
            static2/data/github/shared/ci/manual ARTIFACTORY_USERNAME=username ;
            static2/data/github/shared/ci/manual ARTIFACTORY_ACCESS_TOKEN=access_token

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install Dependencies
        env:
          ARTIFACTORY_ACCESS_TOKEN: ${{ steps.vault.outputs.access_token }}
          ARTIFACTORY_USERNAME: ${{ steps.vault.outputs.username }}
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Build Project
        env:
          ARTIFACTORY_ACCESS_TOKEN: ${{ steps.vault.outputs.access_token }}
          ARTIFACTORY_USERNAME: ${{ steps.vault.outputs.username }}
        run: |
          npm run build --progress=plain

      - name: Run Tests
        run: npm test
